"use client";

import { useState, useCallback, useEffect, useRef } from "react";
import { Plus, Layers, Edit2, Trash2, CheckCircle2, Loader2, Home } from "lucide-react";
import { Input } from "@/components/common";
import { SubUnitDetailedConfigurator } from "../sub-units/SubUnitDetailedConfigurator";
import type { PoolUnit } from "@/types/asset/floor-details.types";
import {
  bulkGenerateSubUnitsAction,
  createChildAssetAction,
  saveFloorDetail,
  fetchFloorsByAsset,
  calculateBuildingCVAction,
} from "@/app/[locale]/assets/municipal-Asset/add-New-Asset/floor-details/actions";
import { useAssetForm } from "../AssetFormContext";
import { toast } from "sonner";

interface UnitPoolPanelProps {
  dropdownOptions: any | null;
  initialSubUnits?: any[];
  initialFloors?: any[];
}

// ── helpers ──────────────────────────────────────────────────────────────────


const TYPE_OPTIONS = [
  { label: "Flat", value: "Flat" },
  { label: "Shop", value: "Shop" },
  { label: "Office", value: "Office" },
];

const typeBadge: Record<string, string> = {
  Flat: "bg-blue-100 text-blue-700",
  Shop: "bg-amber-100 text-amber-700",
  Office: "bg-indigo-100 text-indigo-700",
  Room: "bg-violet-100 text-violet-700",
  Department: "bg-teal-100 text-teal-700",
};

// ─────────────────────────────────────────────────────────────────────────────

export function UnitPoolPanel({ dropdownOptions, initialSubUnits = [], initialFloors = [] }: UnitPoolPanelProps) {
  const { formData, registerSubmitHook, setSubunitFiles } = useAssetForm();

  // ── Pool state ────────────────────────────────────────────────────────────
  const [pool, setPool] = useState<PoolUnit[]>([]);
  const [activeUnit, setActiveUnit] = useState<PoolUnit | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const [parentFloors, setParentFloors] = useState<any[]>(initialFloors);

  // ── Bulk generator form (Type + Count only — asset numbers auto-generated by backend) ─
  const [genType, setGenType] = useState("Flat");
  const [genCount, setGenCount] = useState(1);
  const [isGenerating, setIsGenerating] = useState(false);
  const initializedRef = useRef<string | null>(null); // tracks last initialSubUnits signature

  const departments = dropdownOptions?.departments || [];

  const enhancedDropdownOptions = dropdownOptions ? {
    ...dropdownOptions,
    departments,
  } : { departments };

  // Set parent floors from props if updated
  useEffect(() => {
    if (initialFloors && initialFloors.length > 0) {
      setParentFloors(initialFloors);
    }
  }, [initialFloors]);

  // ── Load and map initial sub-units from props ─────────────────────────────
  useEffect(() => {
    // Build a lightweight signature for the incoming dataset.
    // Re-initialize only when the data identity actually changes (e.g. after Prev/Next
    // brings fresh server data) — not on every re-render.
    const signature = `${initialSubUnits?.length ?? 0}|${(initialSubUnits?.[0] as any)?.assetId ?? (initialSubUnits?.[0] as any)?.id ?? ""}`;
    if (initializedRef.current === signature) return;
    initializedRef.current = signature;

    if (!initialSubUnits || initialSubUnits.length === 0) {
      setPool([]);
      return;
    }

    const existing: PoolUnit[] = initialSubUnits.map((u: any) => {
      // Resolve floor label from dropdownOptions (floor levels loaded from DB)
      const floorDetailsId = u.floorDetailsId ? Number(u.floorDetailsId) : null;
      let floorLabel = "";
      let resolvedFloorLevelId: number | null = null;
      let conYear = "";
      let conType = "";
      let useType = "";
      let subUseType = "";

      if (floorDetailsId) {
        const floorDetail = parentFloors.find((f: any) => Number(f.id) === floorDetailsId);
        const floorLevelId = floorDetail?.floorId ? Number(floorDetail.floorId) : null;
        resolvedFloorLevelId = floorLevelId;

        if (floorDetail) {
          conYear = floorDetail.constructionYear || floorDetail.conYear || "";
          conType = floorDetail.constructionTypeId ? String(floorDetail.constructionTypeId) : (floorDetail.conType ? String(floorDetail.conType) : "");
          useType = floorDetail.typeOfUseId ? String(floorDetail.typeOfUseId) : (floorDetail.useType ? String(floorDetail.useType) : "");
          subUseType = floorDetail.subTypeOfUseId ? String(floorDetail.subTypeOfUseId) : (floorDetail.subUseType ? String(floorDetail.subUseType) : "");
        }

        if (floorLevelId && dropdownOptions?.floorLevels) {
          const match = dropdownOptions.floorLevels.find(
            (f: any) => String(f.value) === String(floorLevelId)
          );
          floorLabel = match ? `${match.label}` : "Selected";
        } else if (dropdownOptions?.floorLevels) {
          const match = dropdownOptions.floorLevels.find(
            (f: any) => String(f.value) === String(floorDetailsId)
          );
          floorLabel = match ? `${match.label}` : "Selected";
        } else {
          floorLabel = "Selected";
        }
      }

      // Resolve department name from departments list
      const deptId = u.departmentId ? Number(u.departmentId) : null;
      const deptName = deptId
        ? (departments.find((d: any) => String(d.value) === String(deptId))?.label || u.departmentName || "")
        : (u.departmentName || "");

      // Unit type: derive from AssetName or unit number code segment (FLAT, SHOP, OFFICE, ROOM, DEPT)
      let unitType = "";
      const numUpper = String(u.unitNo || u.shopUnitName || "").toUpperCase();
      if (numUpper.includes("FLAT")) unitType = "Flat";
      else if (numUpper.includes("SHOP")) unitType = "Shop";
      else if (numUpper.includes("OFFICE")) unitType = "Office";

      if (!unitType) {
        unitType = (u.unitType || "").trim();
      }
      if (!unitType && u.shopUnitName) {
        unitType = (u.shopUnitName as string).split(" ")[0] || "Flat";
      }
      if (!unitType) unitType = "Flat";

      // Map rooms list — use new dimension-based Room shape
      // Try all known field names, then fall back to scanning all array fields
      // to find any that looks like room data (has roomNo or roomType).
      let mappedRooms: any[] = [];
      const ROOM_FIELD_CANDIDATES = ['roomWiseDetails', 'roomDetails', 'roomWiseSubmissions', 'rooms'];
      let roomSource: any[] = [];
      for (const field of ROOM_FIELD_CANDIDATES) {
        if (Array.isArray(u[field]) && u[field].length > 0) {
          roomSource = u[field];
          break;
        }
      }
      // Fallback: scan all array fields for one whose first item has roomNo or roomType
      if (roomSource.length === 0) {
        for (const key of Object.keys(u)) {
          const val = u[key];
          if (Array.isArray(val) && val.length > 0 && val[0] && (val[0].roomNo !== undefined || val[0].roomType !== undefined)) {
            roomSource = val;
            break;
          }
        }
      }

      if (roomSource.length > 0) {
        mappedRooms = roomSource.map((r: any) => {
          const areaSqM = Number(r.areaSqMtr || r.areaSqM || 0);
          const areaSqFt = areaSqM * 10.7639;
          const rOffsets = Array.isArray(r.offsets) ? r.offsets.map((off: any) => ({
            id: off.id,
            shape: off.shape || "Rectangle",
            length: Number(off.length !== undefined ? off.length : (off.radius || 0)),
            width: Number(off.width || 0),
            height: Number(off.height || 0),
            base1: Number(off.base1 || 0),
            base2: Number(off.base2 || 0),
            radius: Number(off.length !== undefined ? off.length : (off.radius || 0)),
            areaSqM: Number(off.areaSqM || 0),
            op: off.op || "Subtract"
          })) : [];

          let netAdjustmentSqM = 0;
          rOffsets.forEach((off: any) => {
            const offArea = Number(off.areaSqM || 0);
            if (off.op === "Add") {
              netAdjustmentSqM += offArea;
            } else {
              netAdjustmentSqM -= offArea;
            }
          });

          const netSqM = Math.max(0, areaSqM + netAdjustmentSqM);
          const netSqFt = netSqM * 10.7639;

          return {
            id: r.id,
            roomNo: r.roomNo,
            roomType: r.roomType,
            shape: r.shape || "Rectangle",
            // Dimensions in meters (stored in DB)
            length: (() => {
              const val = Number(r.lengthMtr || 0);
              if (val === 0 && r.shape === "Square" && areaSqM > 0) {
                return Math.round(Math.sqrt(areaSqM) * 100) / 100;
              }
              return val;
            })(),
            width: Number(r.widthMtr || 0),
            height: Number(r.heightMtr || 0),
            base1: Number(r.base1Mtr || 0),
            base2: Number(r.base2Mtr || 0),
            radius: (() => {
              const val = Number(r.radiusMtr || r.lengthMtr || r.widthMtr || 0);
              if (val === 0 && areaSqM > 0) {
                if (r.shape === "Circle") return Math.round(Math.sqrt(areaSqM / Math.PI) * 100) / 100;
                if (r.shape === "Semi Circle") return Math.round(Math.sqrt((areaSqM * 2) / Math.PI) * 100) / 100;
                if (r.shape === "Quarter") return Math.round(Math.sqrt((areaSqM * 4) / Math.PI) * 100) / 100;
              }
              return val;
            })(),
            // Calculated area
            areaSqM,
            areaSqFt,
            offsets: rOffsets,
            hasOffset: rOffsets.length > 0 ? "Yes" : "No",
            netAreaSqM: netSqM,
            netAreaSqFt: netSqFt,
            count: Number(r.noOfRooms || 1),
            outer: r.outerYesNo ? "Yes" : "No",
            minus: r.minusYesNo ? "Yes" : "No",
            subFloorId: u.subFloorId || u.SubFloorId || null,
          };
        });
      }

      // Map renter details
      const rent = Array.isArray(u.renterDetails)
        ? u.renterDetails[0]
        : (u.renterDetailsList && u.renterDetailsList[0]) || u.renterDetails;

      const renterData = rent ? {
        renterName: rent.renterName || rent.tenantName || "",
        gstNo: rent.gstNo || "",
        aadhaar: rent.aadhaarCardNo || rent.tenantAadhaarNo || "",
        pan: rent.panCardNo || rent.tenantPanCardNo || "",
        mobileNo: rent.mobileNo || rent.tenantMobile || "",
        emailId: rent.emailId || rent.tenantEmail || "",
        rentType: rent.leaseRentType || "",
        leaseStart: rent.fromDate ? rent.fromDate.split("T")[0] : (rent.leaseStartDate ? rent.leaseStartDate.split("T")[0] : ""),
        leaseEnd: rent.toDate ? rent.toDate.split("T")[0] : (rent.leaseEndDate ? rent.leaseEndDate.split("T")[0] : ""),
        duration: rent.duration || "",
        rentFreq: rent.rentFrequency || rent.paymentFrequency || "Monthly",
        rentAmount: rent.rentAmount || rent.monthlyRent || "",
        securityDeposit: rent.securityDeposit || "",
        depositType: rent.depositType || "Refundable",
      } : null;

      return {
        tempId: `db_${u.assetId || u.id}`,
        dbId: (u.assetId || u.id) as number,
        unitNumber: (u.unitNo || u.shopUnitName || `Unit-${u.id}`) as string,
        unitType,
        selectedFloorId: resolvedFloorLevelId || floorDetailsId,
        selectedFloorLabel: floorLabel,
        floorDetailsId: floorDetailsId,
        carpetAreaSqFt: u.totalAreaSqFt ? Math.round(Number(u.totalAreaSqFt) * 100) / 100 : 0,
        rooms: mappedRooms,
        renterDetails: renterData,
        isSaved: true,
        isModified: false,
        departmentId: deptId,
        departmentName: deptName,
        conYear: u.conYear || conYear,
        conType: u.conType || conType,
        useType: u.useType || useType,
        subUseType: u.subUseType || subUseType,
      } as PoolUnit;
    });

    setPool(existing);
  }, [initialSubUnits, parentFloors, dropdownOptions]);

  // ── Generate units — immediately saves to DB, returns real asset IDs ─────────
  const handleGenerate = useCallback(async () => {
    if (!genType) { toast.error("Select a unit type first."); return; }
    if (genCount < 1) { toast.error("Count must be at least 1."); return; }

    const urlParams = typeof window !== "undefined" ? new URLSearchParams(window.location.search) : new URLSearchParams();
    const rawId = Number(formData.id || urlParams.get("id") || urlParams.get("assetId"));
    const parentAssetId = isNaN(rawId) || rawId <= 0 ? 0 : rawId;

    if (!parentAssetId) {
      toast.error("Building not saved yet. Complete Basic Info step first.");
      return;
    }

    setIsGenerating(true);
    const loadingToast = toast.loading(`Generating ${genCount} ${genType} unit(s) in database…`);

    try {
      const res = await bulkGenerateSubUnitsAction({
        parentAssetId,
        type: genType,
        count: genCount,
        // No prefix, no startNumber — backend uses same asset-number logic as main asset
      });

      if (res.success && res.data?.generatedAssets?.length) {
        const newUnits: PoolUnit[] = res.data.generatedAssets.map((ga) => ({
          tempId: `db_${ga.assetId}`,
          dbId: ga.assetId,
          unitNumber: ga.assetNo,
          unitType: genType,
          selectedFloorId: null,
          selectedFloorLabel: "",
          carpetAreaSqFt: 0,
          rooms: [],
          renterDetails: null,
          isSaved: true,   // already in DB
          isModified: false,
        }));

        setPool((prev) => [...prev, ...newUnits]);
        toast.success(
          `${res.data.generatedAssets.length} ${genType} unit(s) created in database. Click Details to configure each.`,
          { id: loadingToast }
        );
      } else {
        const errMsg = res.data?.errors?.join(", ") || res.error || "Generation failed";
        toast.error(errMsg, { id: loadingToast });
      }
    } catch (err: any) {
      toast.error(err.message || "Generation failed.", { id: loadingToast });
    } finally {
      setIsGenerating(false);
    }
  }, [genType, genCount, formData.id]);

  // ── Remove from pool ──────────────────────────────────────────────────────
  const handleRemove = useCallback((tempId: string) => {
    setPool((prev) => prev.filter((u) => u.tempId !== tempId));
  }, []);

  // ── Save unit detail from configurator back to pool ───────────────────────
  const handleSaveUnitDetail = useCallback((updated: any) => {
    // Strip 'rooms' from renterDetails — it's stored at PoolUnit.rooms level
    // to prevent it from overwriting the authoritative room list in the unit prop spread.
    const { rooms: updatedRooms, ...renterDetailsRest } = updated;
    setPool((prev) =>
      prev.map((u) =>
        u.tempId === activeUnit?.tempId
          ? {
            ...u,
            carpetAreaSqFt: Number(updated.carpetAreaSqFeet) || u.carpetAreaSqFt,
            rooms: updatedRooms || u.rooms,        // rooms stored at top-level PoolUnit
            renterDetails: renterDetailsRest,       // no rooms here — prevents overwrite
            selectedFloorId: updated.floorId ? Number(updated.floorId) : null,
            selectedFloorLabel: updated.floorName || "",
            subFloorId: updated.subFloorId ? Number(updated.subFloorId) : null,
            departmentId: updated.departmentId,
            departmentName: updated.departmentName,
            locationAddress: updated.locationAddress,
            locationLat: updated.locationLat,
            locationLng: updated.locationLng,
            conYear: updated.conYear,
            conType: updated.conType,
            useType: updated.useType,
            subUseType: updated.subUseType,
            photoFile: updated.photoFile,
            planFile: updated.planFile,
            isModified: u.isSaved,
          }
          : u
      )
    );
    setActiveUnit(null);
  }, [activeUnit]);

  // ── Save all units to DB (also used as wizard submit hook for SAVE & NEXT) ──
  const handleSaveAll = useCallback(async (): Promise<boolean> => {
    if (pool.length === 0) return true; // nothing to save — proceed to next step

    setIsSaving(true);
    const loadingToast = toast.loading("Saving all units to database...");

    // Resolve parent asset ID from context or URL (inline — avoids hoisting issue)
    const urlParams = typeof window !== "undefined" ? new URLSearchParams(window.location.search) : new URLSearchParams();
    const rawAssetId = Number(formData.id || urlParams.get("id") || urlParams.get("assetId"));
    const parentAssetId = isNaN(rawAssetId) || rawAssetId <= 0 ? 0 : rawAssetId;

    if (!parentAssetId) {
      toast.error("Building not saved yet. Complete Basic Info first.", { id: loadingToast });
      setIsSaving(false);
      return false;
    }

    try {
      const saved: PoolUnit[] = [];
      const errors: string[] = [];
      const unsaved = pool.filter((u) => !u.isSaved || u.isModified);

      // ── Step 0: Auto-create AssetFloorDetails for each unique floor level ──
      // In the new flow there's no pre-configured floor table; floors are created
      // on-the-fly when saving units. We map: FloorMaster.Id → AssetFloorDetails.Id
      const floorDetailsMap = new Map<number, number>(); // floorLevelId → floorDetailsId

      // Load existing floor details for this building first (avoid duplicates)
      try {
        const existRes = await fetchFloorsByAsset(parentAssetId);
        if (existRes.success && Array.isArray(existRes.data)) {
          (existRes.data as any[]).forEach((f: any) => {
            if (f.floorId && f.id) floorDetailsMap.set(Number(f.floorId), Number(f.id));
          });
        }
      } catch { /* ignore — will create new ones */ }

      // Create missing floor details (one per unique floor level in this save batch)
      const uniqueFloorLevels = new Set(
        unsaved.map((u) => u.selectedFloorId).filter((id): id is number => !!id)
      );
      for (const floorLevelId of uniqueFloorLevels) {
        if (!floorDetailsMap.has(floorLevelId)) {
          // Use construction details from the first unit on this floor
          const sample = unsaved.find((u) => u.selectedFloorId === floorLevelId);
          const createRes = await saveFloorDetail({
            isActive: true,
            assetId: parentAssetId,
            floorId: floorLevelId,
            subFloorId: sample?.subFloorId ? Number(sample.subFloorId) : undefined,
            constructionYear: sample?.conYear || String(new Date().getFullYear()),
            assessmentYear: null,
            constructionTypeId: Number(sample?.conType) || 1,
            typeOfUseId: Number(sample?.useType) || 1,
            subTypeOfUseId: Number(sample?.subUseType) || 0,
            carpetAreaSqMeter: 0,
            carpetAreaSqFeet: 0,
            builtUpAreaSqMeter: 0,
            builtUpAreaSqFeet: 0,
            noOfRooms: 0,
            createdBy: 1,
          });
          if (createRes.success && createRes.data) {
            const returnedId = typeof createRes.data === "object"
              ? Number((createRes.data as any).id || (createRes.data as any).items?.id)
              : Number(createRes.data);
            if (returnedId) {
              floorDetailsMap.set(floorLevelId, returnedId);
            }
          }
        }
      }

      // Save each modified/new unit
      for (const unit of unsaved) {
        const roomDetails = unit.rooms.length > 0
          ? unit.rooms.map((r: any) => {
            // r.areaSqM is already in sq.m from new shape-based Room
            // r.area (old) is in SqFt — handle both for backward compat
            const areaSqM = r.areaSqM != null
              ? Number(r.areaSqM)
              : Number(r.area || 0) * 0.092903;
            return {
              roomNo: r.roomNo,
              roomType: r.roomType,
              shape: r.shape || "Rectangle",
              // Dimension fields (in meters) — sent to DB
              lengthMtr: r.length ? Number(r.length) : null,
              widthMtr: r.width ? Number(r.width) : null,
              heightMtr: r.height ? Number(r.height) : null,
              base1Mtr: r.base1 ? Number(r.base1) : null,
              base2Mtr: r.base2 ? Number(r.base2) : null,
              // Area
              areaSqMtr: areaSqM,
              noOfRooms: Number(r.count || 1),
              totalAreaSqMtr: areaSqM * Number(r.count || 1),
              outerYesNo: r.outer === "Yes",
              minusYesNo: r.minus === "Yes" || r.offset === "Yes",
            };
          })
          : null;

        // Duration must be int (months) — not the display string "1 Month, 5 Days"
        const calcDurationMonths = (s: string, e: string): number => {
          if (!s || !e) return 0;
          const start = new Date(s); const end = new Date(e);
          if (isNaN(start.getTime()) || isNaN(end.getTime()) || start > end) return 0;
          let m = (end.getFullYear() - start.getFullYear()) * 12 + (end.getMonth() - start.getMonth());
          if (end.getDate() < start.getDate()) m -= 1;
          return Math.max(0, m);
        };

        const rDetails = unit.renterDetails;
        const rInfo = unit.rentInformation;
        const rentType = rDetails?.rentType || rInfo?.leaseRentType;

        const rentInfo = rentType ? {
          leaseRentType: rentType,
          leaseStart: rDetails?.leaseStart || rInfo?.leaseStart ? new Date(rDetails?.leaseStart || rInfo?.leaseStart).toISOString() : null,
          leaseEnd: rDetails?.leaseEnd || rInfo?.leaseEnd ? new Date(rDetails?.leaseEnd || rInfo?.leaseEnd).toISOString() : null,
          duration: calcDurationMonths(rDetails?.leaseStart || rInfo?.leaseStart || "", rDetails?.leaseEnd || rInfo?.leaseEnd || ""),
          rentFrequency: rDetails?.rentFreq || rInfo?.rentFrequency || "Monthly",
          rentAmount: Number(rDetails?.rentAmount || rInfo?.rentAmount || 0),
          securityDeposit: Number(rDetails?.securityDeposit || rInfo?.securityDeposit || 0),
          depositType: rDetails?.depositType || rInfo?.depositType || "Refundable",
        } : null;

        // Resolve AssetFloorDetails.Id from the map (auto-created above)
        const resolvedFloorDetailsId = unit.selectedFloorId
          ? (floorDetailsMap.get(unit.selectedFloorId) ?? unit.selectedFloorId)
          : undefined;

        const res = await createChildAssetAction({
          parentAssetId,
          assetId: unit.dbId || 0,
          floorDetailsId: resolvedFloorDetailsId,
          floorId: unit.selectedFloorId,
          subFloorId: unit.subFloorId || null,
          unitNo: unit.unitNumber,
          shopUnitName: rDetails?.unitName || null,
          totalAreaSqFt: unit.carpetAreaSqFt,
          departmentId: unit.departmentId ? Number(unit.departmentId) : null,
          renterName: rDetails?.renterName || unit.renterName || null,
          mobileNo: rDetails?.mobileNo || unit.mobileNo || null,
          emailId: rDetails?.emailId || unit.emailId || null,
          gstNo: rDetails?.gstNo || unit.gstNo || null,
          aadhaarCardNo: rDetails?.aadhaar || unit.aadhaarCardNo || null,
          panCardNo: rDetails?.pan || unit.panCardNo || null,
          propertyDescription: rDetails?.propertyDescription || unit.propertyDescription || null,
          rentInformation: rentInfo,
          isRoomWiseValuationActive: roomDetails !== null,
          roomDetails,
          rooms: unit.rooms,
          locationAddress: unit.locationAddress || formData.fullAddress || formData.address || null,
          locationLat: unit.locationLat || (formData.latitude ? String(formData.latitude) : null),
          locationLng: unit.locationLng || (formData.longitude ? String(formData.longitude) : null),
          floorConfiguration: {
            unitAreaSqFt: unit.carpetAreaSqFt,
            calculatedCapitalValue: rDetails?.capitalValue || unit.capitalValue || 0,
          }
        });

        if (res.success && res.data) {
          const savedUnitId = res.data.assetId || unit.dbId;
          if (savedUnitId && (unit.photoFile || unit.planFile)) {
            if (setSubunitFiles) {
              setSubunitFiles((prev) => ({
                ...prev,
                [savedUnitId]: {
                  photoFile: unit.photoFile,
                  planFile: unit.planFile,
                },
              }));
            }
          }

          saved.push({
            ...unit,
            dbId: res.data.assetId || unit.dbId,
            unitNumber: res.data.assetNo || unit.unitNumber,
            isSaved: true,
            isModified: false,
          });
        } else {
          errors.push(`${unit.unitNumber}: ${res.error || "failed"}`);
        }
      }

      // Merge saved back into pool
      setPool((prev) =>
        prev.map((u) => {
          const s = saved.find((sv) => sv.tempId === u.tempId);
          return s ?? u;
        })
      );

      // ── Trigger building-level CV calculation ─────────────────────────────────
      // POST /api/AssetCapitalValue/building/calculate-cv
      // Calculates: floor CVs → sub-unit CVs → building total CV in AssetMaster
      if (parentAssetId > 0) {
        toast.loading("Calculating Capital Values…", { id: loadingToast });
        try {
          await calculateBuildingCVAction(parentAssetId, true);
        } catch { /* non-fatal — CV visible on next step */ }
      }

      if (errors.length > 0) {
        toast.warning(`Saved ${saved.length} units. ${errors.length} failed: ${errors.join(", ")}`, { id: loadingToast });
        return false;   // partial failure — stay on page so user can retry
      }
      toast.success(`All ${saved.length} unit(s) saved. Proceeding…`, { id: loadingToast });
      return true;      // all saved — footer will navigate to next step
    } catch (err: any) {
      toast.error(err.message || "Save failed.", { id: loadingToast });
      return false;
    } finally {
      setIsSaving(false);
    }
  }, [pool, formData.id]);

  // ── Register handleSaveAll as the SAVE & NEXT submit hook ─────────────────
  useEffect(() => {
    if (registerSubmitHook) registerSubmitHook(handleSaveAll);
    return () => { if (registerSubmitHook) registerSubmitHook(null); };
  }, [registerSubmitHook, handleSaveAll]);

  // ─────────────────────────────────────────────────────────────────────────
  // Render
  // ─────────────────────────────────────────────────────────────────────────

  const savedCount = pool.filter((u) => u.isSaved).length;
  const unsavedCount = pool.filter((u) => !u.isSaved || u.isModified).length;

  if (activeUnit) {
    return (
      <div className="fixed inset-0 z-[60] bg-slate-50 flex flex-col">
        <SubUnitDetailedConfigurator
          unit={(() => {
              // Destructure 'rooms' out of renterDetails so it cannot override activeUnit.rooms
              const { rooms: _rdRooms, ...renterRest } = activeUnit.renterDetails || {};
              void _rdRooms; // intentionally unused — we always use activeUnit.rooms
              return {
                ...activeUnit,
                ...renterRest,
                // These always win — set explicitly after the renterDetails spread
                unitNumber: activeUnit.unitNumber,
                unitType: activeUnit.unitType,
                carpetAreaSqFeet: activeUnit.carpetAreaSqFt,
                rooms: activeUnit.rooms,       // ← authoritative room list from pool
                floorId: activeUnit.selectedFloorId,
                floorDetailsId: activeUnit.floorDetailsId,
                subFloorId: activeUnit.subFloorId,
                departmentId: activeUnit.departmentId,
                locationAddress: activeUnit.locationAddress,
                locationLat: activeUnit.locationLat,
                locationLng: activeUnit.locationLng,
                conYear: activeUnit.conYear,
                conType: activeUnit.conType,
                useType: activeUnit.useType,
                subUseType: activeUnit.subUseType,
                photoFile: activeUnit.photoFile,
                planFile: activeUnit.planFile,
              };
            })()}
          floors={parentFloors}
          parentBuildingName={formData.assetName || "Unit Configuration"}
          onSave={handleSaveUnitDetail}
          onCancel={() => setActiveUnit(null)}
          dropdownOptions={enhancedDropdownOptions}
        />
      </div>
    );
  }

  return (
    <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2.5 bg-[#0f172a] text-white">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-blue-500/20 rounded-lg"><Home className="size-4 text-blue-400" /></div>
          <div>
            <h3 className="text-xs font-black uppercase tracking-wider">Unit Management Pool</h3>
            <p className="text-[9px] text-slate-400 font-semibold uppercase tracking-widest mt-0.5">
              Generate units directly against the building → configure their details
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-widest">
          <span className="px-2 py-0.5 bg-blue-500/20 text-blue-300 rounded">{pool.length} total</span>
          {savedCount > 0 && <span className="px-2 py-0.5 bg-emerald-500/20 text-emerald-300 rounded">{savedCount} saved</span>}
        </div>
      </div>

      <div className="p-3 space-y-3">
        <div className="bg-slate-50 rounded-xl border border-slate-200 p-3 space-y-2">
          <div className="flex items-center gap-2 mb-1">
            <span className="flex items-center justify-center size-5 rounded-full bg-blue-600 text-white text-[10px] font-black">1</span>
            <span className="text-[10px] font-black text-slate-700 uppercase tracking-wider">Generate Units</span>
          </div>
          {/* Only Type + Count — asset numbers generated same way as main asset (Akola01-BLDG-MUNI-FLAT-0001) */}
          <div className="flex flex-wrap items-end gap-3">
            <div className="w-56">
              <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wide mb-1">Type</label>
              <select
                value={genType}
                onChange={(e) => setGenType(e.target.value)}
                className="h-8 w-full rounded-lg border border-slate-300 bg-white px-2 text-xs text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-200 cursor-pointer"
              >
                {TYPE_OPTIONS.map((o) => (
                  <option key={o.value} value={o.value}>{o.label}</option>
                ))}
              </select>
            </div>
            <div className="w-32">
              <label className="block text-[10px] font-bold text-slate-500 uppercase tracking-wide mb-1">Count</label>
              <Input
                type="number"
                min={1}
                value={genCount === 0 ? "" : genCount}
                onChange={(e) => setGenCount(Math.max(1, Number(e.target.value)))}
                className="h-8 text-xs px-2 font-bold text-blue-700"
              />
            </div>
            <div className="w-44">
              <button
                type="button"
                onClick={handleGenerate}
                disabled={isGenerating || !genType || genCount < 1}
                className={`w-full h-8 rounded-lg text-[10px] font-black uppercase tracking-wider flex items-center justify-center gap-1 transition-colors shadow-sm ${isGenerating || !genType || genCount < 1
                  ? "bg-blue-300 cursor-not-allowed text-white"
                  : "bg-blue-600 hover:bg-blue-700 text-white"
                  }`}>
                {isGenerating
                  ? <><Loader2 className="size-3.5 animate-spin" /> Generating...</>
                  : <><Plus className="size-3.5" strokeWidth={3} /> Generate {genCount}</>
                }
              </button>
            </div>
          </div>
        </div>

        <div className="space-y-1.5">
          <div className="flex items-center gap-2">
            <span className="flex items-center justify-center size-5 rounded-full bg-blue-600 text-white text-[10px] font-black">2</span>
            <span className="text-[10px] font-black text-slate-700 uppercase tracking-wider">Configure Unit Details</span>
          </div>

          {pool.length === 0 ? (
            <div className="py-8 text-center border-2 border-dashed border-slate-200 rounded-xl bg-slate-50">
              <Layers className="size-6 text-slate-300 mx-auto mb-1.5" />
              <p className="text-xs font-bold text-slate-400">No units generated yet</p>
            </div>
          ) : (
            <div className="rounded-xl border border-slate-200 overflow-hidden">
              <table className="w-full text-xs text-left">
                <thead>
                  <tr className="bg-slate-800 text-slate-200 text-xs font-black uppercase tracking-widest">
                    <th className="px-3 py-2">Unit Number</th>
                    <th className="px-3 py-2">Type</th>
                    <th className="px-3 py-2">Floor</th>
                    <th className="px-3 py-2">Department</th>
                    <th className="px-3 py-2 text-right">Area (SqFt)</th>
                    <th className="px-3 py-2 text-center">Status</th>
                    <th className="px-3 py-2 text-center">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {pool.map((unit) => (
                    <tr key={unit.tempId} className={`hover:bg-slate-50/60 transition-colors ${unit.isSaved && !unit.isModified ? "bg-emerald-50/30" : ""}`}>
                      <td className="px-3 py-2 font-bold text-slate-800">{unit.unitNumber}</td>
                      <td className="px-3 py-2">
                        <span className={`px-2 py-0.5 rounded text-[9px] font-black uppercase tracking-wide ${typeBadge[unit.unitType] || "bg-slate-100 text-slate-600"}`}>
                          {unit.unitType}
                        </span>
                      </td>
                      <td className="px-3 py-2 font-semibold text-slate-600">
                        {unit.selectedFloorLabel || "—"}
                      </td>
                      <td className="px-3 py-2 font-semibold text-slate-600 truncate max-w-[120px]" title={(unit.departmentId ? departments.find((d: any) => String(d.value) === String(unit.departmentId))?.label : "") || unit.departmentName || ""}>
                        {(unit.departmentId ? departments.find((d: any) => String(d.value) === String(unit.departmentId))?.label : "") || unit.departmentName || "—"}
                      </td>
                      <td className="px-3 py-2 text-right font-mono text-[10px]">
                        {unit.carpetAreaSqFt > 0
                          ? <span className="font-bold text-slate-700">{unit.carpetAreaSqFt.toFixed(2)}</span>
                          : <span className="text-slate-400 italic text-[9px]">pending</span>
                        }
                      </td>
                      <td className="px-3 py-2 text-center">
                        {unit.isSaved && !unit.isModified
                          ? <span title="Saved to database"><CheckCircle2 className="size-4 text-emerald-500 mx-auto" /></span>
                          : unit.isModified
                            ? <span className="text-[9px] font-bold text-amber-600 uppercase">Modified</span>
                            : <span className="text-[9px] font-bold text-slate-400 uppercase">Pending</span>
                        }
                      </td>
                      <td className="px-3 py-1.5 text-center">
                        <div className="flex items-center justify-center gap-1.5">
                          <button
                            type="button"
                            onClick={() => setActiveUnit(unit)}
                            className="px-2 py-1 rounded-lg text-[9px] font-bold text-blue-600 bg-blue-50 hover:bg-blue-100 border border-blue-200 transition-colors flex items-center gap-1"
                            title="Configure Unit Details">
                            <Edit2 className="size-3" /> Details
                          </button>
                          <button
                            type="button"
                            onClick={() => handleRemove(unit.tempId)}
                            className="p-1 rounded-lg text-slate-400 hover:text-red-500 hover:bg-red-50 border border-transparent hover:border-red-200 transition-colors">
                            <Trash2 className="size-3" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Status hint — saving is triggered by the SAVE & NEXT button in the footer */}
        {pool.length > 0 && (
          <div className="flex items-center gap-2 pt-1 border-t border-slate-100 text-[10px]">
            {isSaving && <><Loader2 className="size-3.5 animate-spin text-blue-500" /><span className="text-blue-600 font-bold">Saving…</span></>}
            {!isSaving && unsavedCount > 0 && <span className="text-amber-600 font-semibold">{unsavedCount} unit(s) will be saved when you click SAVE & NEXT</span>}
            {!isSaving && unsavedCount === 0 && <><CheckCircle2 className="size-3.5 text-emerald-500" /><span className="text-emerald-600 font-bold">All units saved ✓</span></>}
          </div>
        )}
      </div>
    </div>
  );
}
