import { PagedResponse } from "../common.types";

/** 
 * Form model for creating and editing asset categories
 */
export interface AssetCategoryFormModel {
  id?: number;
  categoryCode: string;
  categoryName: string;
  description: string;
  isActive: boolean;
  isMovable?: boolean;
  hasFloorDetails?: boolean;
  hasInventory?: boolean;
  /** If hasInventory is true, this determines if it's strictly mandatory */
  isInventoryMandatory?: boolean;
  hasLegalCompliance?: boolean;
  valuationType?: string;
  /** Format of the code expected by backend validation (e.g. "1") */
  codeFormat?: string;
}

/**
 * Interface for the Asset Category record as returned by the backend API.
 */
export interface AssetCategoryApiRecord {
  /** Unique numeric identifier generated by the backend */
  id: number;
  /** Human-readable name for the category */
  categoryName: string;
  /** Alphanumeric code identifier */
  categoryCode: string;
  description: string;
  /** Determines if the category is currently available for selection */
  isActive: boolean;
  isMovable: boolean;
  hasFloorDetails: boolean;
  hasInventory: boolean;
  /** If hasInventory is true, this determines if it's strictly mandatory */
  isInventoryMandatory: boolean;
  hasLegalCompliance: boolean;
  valuationType: string;
  createdDate?: string;
  updatedDate?: string | null;
  /** Code format requirement enforced by the backend API validation rules */
  codeFormat?: string;
}

/**
 * Normalized model for Asset Category
 */
export interface AssetCategory {
  id: number;
  categoryCode: string;
  categoryName: string;
  description: string;
  isActive: boolean;
  isMovable: boolean;
  hasFloorDetails: boolean;
  hasInventory: boolean;
  isInventoryMandatory: boolean;
  hasLegalCompliance: boolean;
  valuationType: string;
  createdDate: string;
  updatedDate: string | null;
}

/**
 * Props for Asset Category list component
 */
export interface AssetCategoryProps extends Omit<PagedResponse<AssetCategory>, 'items' | 'hasPrevious' | 'hasNext'> {
  data: AssetCategory[];
}

/**
 * Parameters for fetching asset categories
 */
export interface AssetCategoryParams {
  PageNumber?: number;
  PageSize?: number;
  SearchTerm?: string;
  IsActive?: string;
  SortBy?: string;
  SortOrder?: 'asc' | 'desc';
}
