import { PagedResponse } from "../common.types";

/** 
 * Form model for creating and editing asset types
 */
export interface AssetTypeFormModel {
  id?: number;
  typeCode: string;
  typeName: string;
  categoryId: number;
  description: string;
  isActive: boolean;
  /** Format of the code expected by backend validation (e.g. "1") */
  codeFormat?: string;
}

/**
 * Interface for the Asset Type record as returned by the backend API.
 */
export interface AssetTypeApiRecord {
  /** Unique numeric identifier generated by the backend */
  id: number;
  /** Human-readable name for the type */
  typeName: string;
  /** Alphanumeric code identifier */
  typeCode: string;
  /** Reference ID to the parent Asset Category */
  categoryId: number;
  categoryName?: string;
  description: string;
  /** Determines if the type is currently available for selection */
  isActive: boolean;
  createdDate?: string;
  updatedDate?: string | null;
  /** Code format requirement enforced by the backend API validation rules */
  codeFormat?: string;
  allowUnitRegistration?: boolean;
  allowRoomRegistration?: boolean;
}

/**
 * Normalized model for Asset Type
 */
export interface AssetType {
  id: number;
  typeCode: string;
  typeName: string;
  categoryId: number;
  categoryName: string;
  description: string;
  isActive: boolean;
  allowUnitRegistration: boolean;
  allowRoomRegistration: boolean;
  createdDate: string;
  updatedDate: string | null;
}

/**
 * Props for Asset Type list component
 */
export interface AssetTypeProps extends Omit<PagedResponse<AssetType>, 'items' | 'hasPrevious' | 'hasNext'> {
  data: AssetType[];
}

/**
 * Parameters for fetching asset types
 */
export interface AssetTypeParams {
  PageNumber?: number;
  PageSize?: number;
  SearchTerm?: string;
  CategoryId?: number;
  SortBy?: string;
  SortOrder?: 'asc' | 'desc';
  IsActive?: string;
}
