export type AssetRegisterRow = {
  id: number | null;
  assetId: string;
  authorityName: string;
  organizationName: string;
  departmentName: string;
  assetCode: string;
  assetName: string;
  categoryName: string;
  assetTypeName: string;
  parentAssetName: string;
  address: string;
  wardName: string;
  zoneName: string;
  latitude: string;
  longitude: string;
  csn: string;
  hasLift: string;
  purchaseDate: string;
  marketValueDate: string;
  capitalValue: string;
  lastCVCalculationDate: string;
  currentBookValue: string;
  depreciation: string;
  netBookValue: string;
  lifeYears: string;
  depreciationRate: string;
  isRevenueGenerating: string;
  operationalControl: string;
  fieldValues: string;
  occupancyStatus: string;
  ownershipType: string;
  assetCondition: string;
  status: string;
  purchaseValue: string;
  marketValue: string;
  builtUpAreaSqMeter: string;
  carpetAreaSqMeter: string;
  landAreaSqMeter: string;
  createdDate: string;
};

export type AssetRegisterApiRecord = {
  id?: number | string;
  assetCode?: string;
  assetNo?: string;
  assetId?: string;
  assetName?: string;
  name?: string;
  categoryName?: string;
  assetCategoryName?: string;
  assetTypeName?: string;
  departmentName?: string;
  department?: string;
  authorityName?: string;
  organizationName?: string;
  status?: string;
  isActive?: boolean;
  assetCondition?: string;
  ownershipType?: string;
  occupancyStatus?: string;
  address?: string;
  wardName?: string;
  zoneName?: string;
  parentAssetName?: string;
  latitude?: number | string | null;
  longitude?: number | string | null;
  csn?: string;
  hasLift?: boolean | string | null;
  purchaseDate?: string | null;
  marketValueDate?: string | null;
  capitalValue?: number | string | null;
  lastCVCalculationDate?: string | null;
  currentBookValue?: number | string | null;
  depreciationRate?: number | string | null;
  isRevenueGenerating?: boolean | string | null;
  operationalControl?: string | null;
  fieldValues?: unknown;
  purchaseValue?: number | string | null;
  marketValue?: number | string | null;
  depreciation?: number | string | null;
  netBookValue?: number | string | null;
  builtUpAreaSqMeter?: number | string | null;
  carpetAreaSqMeter?: number | string | null;
  landAreaSqMeter?: number | string | null;
  createdDate?: string;
  createdAt?: string;
};

export type AssetRegisterPageResult = {
  items: AssetRegisterApiRecord[];
  totalCount: number;
};
